name: Terraform CI/CD

on:
  push:
    branches:
      - 'main'
      - '**' # triggers on all branches

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: enviroment/prod

    env:
      ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
      TF_VAR_stg: ${{ fromJSON(secrets.AZURE_CREDENTIALS).stg }}
      TF_VAR_location: ${{ fromJSON(secrets.AZURE_CREDENTIALS).location }}
      TF_VAR_RG: ${{ fromJSON(secrets.AZURE_CREDENTIALS).RG }}
      TF_VAR_account_tier: ${{ fromJSON(secrets.AZURE_CREDENTIALS).account_tier }}
      TF_VAR_account_replication_type: ${{ fromJSON(secrets.AZURE_CREDENTIALS).account_replication_type }}
      ARM_USE_CLI: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Format check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
